name: semantic-release

on:
  workflow_run:
    workflows: ["Tests"]
    branches: [main]
    types:
      - completed

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  semantic-release:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4.1.7
      - id: release
        uses: ahmadnassri/action-semantic-release@v2.2.8
        with:
          config: ${{ github.workspace }}/.release.json
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
