name: Tests
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - run: npm run check
      - run: npm run test:unit -- --run
      - name: Svelte 4 e2e tests
        working-directory: e2e/svelte-4
        run: |
          npm ci
          npm run check
          npx playwright install
          npm run test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: e2e/svelte-4/playwright-report/
          retention-days: 30
